path = require('path')

rimraf = require('rimraf')
gulp = require('gulp')
mocha = require('gulp-mocha')
gutil = require('gulp-util')
coffeelint = require('gulp-coffeelint')
coffee = require('gulp-coffee')
insert = require('gulp-insert')
runSequence = require('run-sequence')
browserify = require('browserify')
uglify = require('gulp-uglify')
source = require('vinyl-source-buffer')

packageJSON = require('./package.json')

{ loadEnv } = require('./tests/util')

OPTIONS =
	config:
		coffeelint: path.join(__dirname, 'coffeelint.json')
		browserLibraryName: 'resin-sdk'
	files:
		coffee: [ 'lib/**/*.coffee', 'tests/**/*.coffee', 'gulpfile.coffee' ]
		app: 'lib/**/*.coffee'
		tests: 'tests/*.spec.coffee'
		browserEntry: 'resin.js'
		browserOutput: 'resin-browser.js'
		browserMinifiedOutput: 'resin-browser.min.js'
	directories:
		doc: 'doc/'
		build: 'build/'

gulp.task 'clean-build', (callback) ->
	rimraf(OPTIONS.directories.build, callback)

gulp.task 'test', ->
	loadEnv()
	gulp.src(OPTIONS.files.tests, read: false)
		.pipe(mocha({
			reporter: 'spec',
			compilers: 'coffee:coffee-script/register'
		}))

gulp.task 'lint', ->
	gulp.src(OPTIONS.files.coffee)
		.pipe(coffeelint({
			optFile: OPTIONS.config.coffeelint
		}))
		.pipe(coffeelint.reporter())

gulp.task 'build', (callback) ->
	runSequence('lint', 'clean-build', 'build-node', 'build-browser', callback)

gulp.task 'build-node', ->
	gulp.src(OPTIONS.files.app)
		.pipe(coffee(header: true, bare: true)).on('error', gutil.log)
		.pipe(gulp.dest(OPTIONS.directories.build))

gulp.task 'build-browser', ['build-node'], ->
	bundle = browserify
		entries: OPTIONS.files.browserEntry,
		basedir: OPTIONS.directories.build
		standalone: OPTIONS.config.browserLibraryName

	# These modules are referenced in the code, but only get used in Node:
	.exclude('fs')
	.exclude('path')
	.exclude('resin-settings-client')
	.exclude('node-localstorage')
	.exclude('rindle')
	.exclude('zlib')
	.exclude('progress-stream')
	.bundle()

	bundle
		.pipe(source(OPTIONS.files.browserOutput))
		.pipe(insert.prepend('// Generated by browserify\n'))
		.pipe(gulp.dest(OPTIONS.directories.build))

	bundle
		.pipe(source(OPTIONS.files.browserMinifiedOutput))
		.pipe(uglify())
		.pipe(gulp.dest(OPTIONS.directories.build))

gulp.task 'watch', [ 'build' ], ->
	gulp.watch([ OPTIONS.files.coffee ], [ 'lint' ])
