// These types were generated by @balena/abstract-sql-to-typescript v5.1.2

import type { Types } from '@balena/abstract-sql-to-typescript';

export interface Actor {
	Read: {
		id: Types['Integer']['Read'];
		is_of__user?: Array<User['Read']>;
		is_of__application?: Array<Application['Read']>;
		is_of__device?: Array<Device['Read']>;
		api_key?: Array<ApiKey['Read']>;
	};
	Write: Record<string, never>;
}

export interface User {
	Read: {
		created_at: Types['Date Time']['Read'];
		id: Types['Integer']['Read'];
		actor: { __id: Actor['Read']['id'] } | [Actor['Read']];
		username: Types['Short Text']['Read'];
		has_legacy_link_to__organization:
			| { __id: Organization['Read']['id'] }
			| [Organization['Read']]
			| []
			| null;
		user__has__public_key?: Array<UserHasPublicKey['Read']>;
		user_public_key?: Array<UserHasPublicKey['Read']>;
		user__is_member_of__organization?: Array<OrganizationMembership['Read']>;
		organization_membership?: Array<OrganizationMembership['Read']>;
		user__is_member_of__team?: Array<TeamMembership['Read']>;
		team_membership?: Array<TeamMembership['Read']>;
		user__is_member_of__application?: Array<UserIsMemberOfApplication['Read']>;
		user_application_membership?: Array<UserIsMemberOfApplication['Read']>;
		is_member_of__organization?: Array<OrganizationMembership['Read']>;
		is_member_of__team?: Array<TeamMembership['Read']>;
		is_member_of__application?: Array<UserIsMemberOfApplication['Read']>;
		is_of__user__is_member_of__organization?: Array<
			OrganizationMembership['Read']
		>;
		is_of__organization_membership?: Array<OrganizationMembership['Read']>;
		is_of__user__is_member_of__application?: Array<
			UserIsMemberOfApplication['Read']
		>;
		is_of__user_application_membership?: Array<
			UserIsMemberOfApplication['Read']
		>;
		includes__user__is_member_of__organization?: Array<
			OrganizationMembership['Read']
		>;
		includes__organization_membership?: Array<OrganizationMembership['Read']>;
		includes__user__is_member_of__application?: Array<
			UserIsMemberOfApplication['Read']
		>;
		includes__user_application_membership?: Array<
			UserIsMemberOfApplication['Read']
		>;
		creates__invitee__is_invited_to__application?: Array<
			InviteeIsInvitedToApplication['Read']
		>;
		creates__application_invite?: Array<InviteeIsInvitedToApplication['Read']>;
		creates__invitee__is_invited_to__organization?: Array<
			InviteeIsInvitedToOrganization['Read']
		>;
		creates__organization_invite?: Array<
			InviteeIsInvitedToOrganization['Read']
		>;
		creates__release?: Array<Release['Read']>;
		owns__social_service_account?: Array<SocialServiceAccount['Read']>;
		owns__device?: Array<Device['Read']>;
		owns__recovery_two_factor?: Array<RecoveryTwoFactor['Read']>;
		owns__saml_account?: Array<SamlAccount['Read']>;
		has_direct_access_to__application?: Array<
			UserHasDirectAccessToApplication['Read']
		>;
		user_profile?: Array<UserProfile['Read']>;
	};
	Write: Record<string, never>;
}

export interface ApiKey {
	Read: {
		created_at: Types['Date Time']['Read'];
		id: Types['Integer']['Read'];
		expiry_date: Types['Date Time']['Read'] | null;
		is_of__actor: { __id: Actor['Read']['id'] } | [Actor['Read']];
		name: Types['Short Text']['Read'] | null;
		description: Types['Text']['Read'] | null;
	};
	Write: {
		expiry_date: Types['Date Time']['Write'] | null;
		name: Types['Short Text']['Write'] | null;
		description: Types['Text']['Write'] | null;
	};
}

export interface ApplicationType {
	Read: {
		id: Types['Integer']['Read'];
		name: Types['Short Text']['Read'];
		supports_web_url: Types['Boolean']['Read'];
		supports_multicontainer: Types['Boolean']['Read'];
		supports_gateway_mode: Types['Boolean']['Read'];
		needs__os_version_range: Types['Short Text']['Read'] | null;
		requires_payment: Types['Boolean']['Read'];
		is_legacy: Types['Boolean']['Read'];
		slug: Types['Short Text']['Read'];
		description: Types['Text']['Read'] | null;
		maximum_device_count: Types['Integer']['Read'] | null;
		is_of__application?: Array<Application['Read']>;
	};
	Write: Record<string, never>;
}

export interface CpuArchitecture {
	Read: {
		id: Types['Integer']['Read'];
		slug: Types['Short Text']['Read'];
		device_type?: Array<DeviceType['Read']>;
		is_supported_by__device_type?: Array<DeviceType['Read']>;
	};
	Write: Record<string, never>;
}

export interface DeviceFamily {
	Read: {
		id: Types['Integer']['Read'];
		slug: Types['Short Text']['Read'];
		name: Types['Short Text']['Read'];
		is_manufactured_by__device_manufacturer:
			| { __id: DeviceManufacturer['Read']['id'] }
			| [DeviceManufacturer['Read']]
			| []
			| null;
		device_type?: Array<DeviceType['Read']>;
	};
	Write: Record<string, never>;
}

export interface DeviceManufacturer {
	Read: {
		id: Types['Integer']['Read'];
		slug: Types['Short Text']['Read'];
		name: Types['Short Text']['Read'];
	};
	Write: Record<string, never>;
}

export interface DeviceType {
	Read: {
		id: Types['Integer']['Read'];
		slug: Types['Short Text']['Read'];
		name: Types['Short Text']['Read'];
		is_of__cpu_architecture:
			| { __id: CpuArchitecture['Read']['id'] }
			| [CpuArchitecture['Read']];
		logo: Types['Text']['Read'] | null;
		contract: Types['JSON']['Read'] | null;
		belongs_to__device_family:
			| { __id: DeviceFamily['Read']['id'] }
			| [DeviceFamily['Read']]
			| []
			| null;
		is_private: Types['Boolean']['Read'];
		is_default_for__application?: Array<Application['Read']>;
		device?: Array<Device['Read']>;
		describes__device?: Array<Device['Read']>;
		describes__public_device?: Array<PublicDevice['Read']>;
		device_type__is_referenced_by__alias?: Array<DeviceTypeAlias['Read']>;
		device_type_alias?: Array<DeviceTypeAlias['Read']>;
		supports__cpu_architecture:
			| { __id: CpuArchitecture['Read']['id'] }
			| [CpuArchitecture['Read']];
		is_referenced_by__alias?: Array<DeviceTypeAlias['Read']>;
		is_accessible_privately_by__organization?: Array<
			OrganizationHasPrivateAccessToDeviceType['Read']
		>;
		public_device?: Array<PublicDevice['Read']>;
		device_history?: Array<DeviceHistory['Read']>;
	};
	Write: Record<string, never>;
}

export interface Image {
	Read: {
		created_at: Types['Date Time']['Read'];
		id: Types['Integer']['Read'];
		start_timestamp: Types['Date Time']['Read'];
		end_timestamp: Types['Date Time']['Read'] | null;
		dockerfile: Types['Text']['Read'] | null;
		is_a_build_of__service: { __id: Service['Read']['id'] } | [Service['Read']];
		image_size: Types['Big Integer']['Read'] | null;
		is_stored_at__image_location: Types['Short Text']['Read'];
		project_type: Types['Short Text']['Read'] | null;
		error_message: Types['Text']['Read'] | null;
		build_log: Types['Text']['Read'] | null;
		push_timestamp: Types['Date Time']['Read'] | null;
		status: Types['Short Text']['Read'];
		content_hash: Types['Short Text']['Read'] | null;
		contract: Types['JSON']['Read'] | null;
		device__installs__image?: Array<ImageInstall['Read']>;
		image_install?: Array<ImageInstall['Read']>;
		is_part_of__release?: Array<ImageIsPartOfRelease['Read']>;
		image__is_part_of__release?: Array<ImageIsPartOfRelease['Read']>;
		release_image?: Array<ImageIsPartOfRelease['Read']>;
		is_a_build_of__application__has__service_name:
			| { __id: Service['Read']['id'] }
			| [Service['Read']];
		is__origin__of__delta?: Array<Delta['Read']>;
		is_produced_by__delta?: Array<Delta['Read']>;
	};
	Write: {
		start_timestamp: Types['Date Time']['Write'];
		end_timestamp: Types['Date Time']['Write'] | null;
		dockerfile: Types['Text']['Write'] | null;
		is_a_build_of__service: Types['Integer']['Write'];
		image_size: Types['Big Integer']['Write'] | null;
		is_stored_at__image_location: Types['Short Text']['Write'];
		project_type: Types['Short Text']['Write'] | null;
		error_message: Types['Text']['Write'] | null;
		build_log: Types['Text']['Write'] | null;
		push_timestamp: Types['Date Time']['Write'] | null;
		status: Types['Short Text']['Write'];
		content_hash: Types['Short Text']['Write'] | null;
		contract: Types['JSON']['Write'] | null;
	};
}

export interface Organization {
	Read: {
		created_at: Types['Date Time']['Read'];
		id: Types['Integer']['Read'];
		name: Types['Short Text']['Read'];
		handle: Types['Short Text']['Read'];
		company_name: Types['Text']['Read'] | null;
		billing_account_code: Types['Short Text']['Read'] | null;
		has_past_due_invoice_since__date: Types['Date Time']['Read'] | null;
		is_frozen: Types['Boolean']['Read'];
		industry: Types['Short Text']['Read'] | null;
		website: Types['Text']['Read'] | null;
		logo_image: Types['WebResource']['Read'] | null;
		is_using__billing_version: Types['Text']['Read'] | null;
		is_enforcing_saml_login: Types['Boolean']['Read'];
		user__is_member_of__organization?: Array<OrganizationMembership['Read']>;
		organization_membership?: Array<OrganizationMembership['Read']>;
		includes__user?: Array<OrganizationMembership['Read']>;
		includes__user__is_member_of__organization?: Array<
			OrganizationMembership['Read']
		>;
		includes__organization_membership?: Array<OrganizationMembership['Read']>;
		includes__organization__is_authorized_by__identity_provider?: Array<
			IdentityProviderMembership['Read']
		>;
		includes__identity_provider_membership?: Array<
			IdentityProviderMembership['Read']
		>;
		organization__has_private_access_to__device_type?: Array<
			OrganizationHasPrivateAccessToDeviceType['Read']
		>;
		organization__owns_credit_notification_for__feature?: Array<
			OrganizationCreditNotification['Read']
		>;
		organization_credit_notification?: Array<
			OrganizationCreditNotification['Read']
		>;
		organization__is_authorized_by__identity_provider?: Array<
			IdentityProviderMembership['Read']
		>;
		identity_provider_membership?: Array<IdentityProviderMembership['Read']>;
		is_of__application?: Array<Application['Read']>;
		is_of__organization__is_authorized_by__identity_provider?: Array<
			IdentityProviderMembership['Read']
		>;
		is_of__identity_provider_membership?: Array<
			IdentityProviderMembership['Read']
		>;
		application?: Array<Application['Read']>;
		owns__team?: Array<Team['Read']>;
		owns__credit_bundle?: Array<CreditBundle['Read']>;
		invitee__is_invited_to__organization?: Array<
			InviteeIsInvitedToOrganization['Read']
		>;
		organization_invite?: Array<InviteeIsInvitedToOrganization['Read']>;
		invitee?: Array<InviteeIsInvitedToOrganization['Read']>;
		includes_legacy_link_to__user?: Array<User['Read']>;
		has_private_access_to__device_type?: Array<
			OrganizationHasPrivateAccessToDeviceType['Read']
		>;
		owns_credit_notification_for__feature?: Array<
			OrganizationCreditNotification['Read']
		>;
		subscription?: Array<Subscription['Read']>;
		is_authorized_by__identity_provider?: Array<
			IdentityProviderMembership['Read']
		>;
	};
	Write: {
		name: Types['Short Text']['Write'];
		handle: Types['Short Text']['Write'];
		company_name: Types['Text']['Write'] | null;
		industry: Types['Short Text']['Write'] | null;
		website: Types['Text']['Write'] | null;
		logo_image: Types['WebResource']['Write'] | null;
		is_enforcing_saml_login: Types['Boolean']['Write'];
	};
}

export interface ServiceInstance {
	Read: {
		id: Types['Integer']['Read'];
		ip_address: Types['Short Text']['Read'];
		manages__device?: Array<Device['Read']>;
	};
	Write: Record<string, never>;
}

export interface Application {
	Read: {
		created_at: Types['Date Time']['Read'];
		id: Types['Integer']['Read'];
		actor: { __id: Actor['Read']['id'] } | [Actor['Read']];
		should_track_latest_release: Types['Boolean']['Read'];
		is_of__class: 'fleet' | 'block' | 'app';
		organization: { __id: Organization['Read']['id'] } | [Organization['Read']];
		app_name: Types['Text']['Read'];
		slug: Types['Short Text']['Read'];
		is_for__device_type:
			| { __id: DeviceType['Read']['id'] }
			| [DeviceType['Read']];
		should_be_running__release:
			| { __id: Release['Read']['id'] }
			| [Release['Read']]
			| []
			| null;
		application_type:
			| { __id: ApplicationType['Read']['id'] }
			| [ApplicationType['Read']];
		is_host: Types['Boolean']['Read'];
		is_archived: Types['Boolean']['Read'];
		uuid: Types['Text']['Read'];
		is_public: Types['Boolean']['Read'];
		is_accessible_by_support_until__date: Types['Date Time']['Read'] | null;
		is_discoverable: Types['Boolean']['Read'];
		is_stored_at__repository_url: Types['Text']['Read'] | null;
		application__has__env_var_name?: Array<
			ApplicationEnvironmentVariable['Read']
		>;
		application_environment_variable?: Array<
			ApplicationEnvironmentVariable['Read']
		>;
		application__has__config_var_name?: Array<
			ApplicationConfigVariable['Read']
		>;
		application_config_variable?: Array<ApplicationConfigVariable['Read']>;
		application__has__service_name?: Array<Service['Read']>;
		service?: Array<Service['Read']>;
		application__has__tag_key?: Array<ApplicationTag['Read']>;
		application_tag?: Array<ApplicationTag['Read']>;
		application__has__domain?: Array<ApplicationDomainMapping['Read']>;
		application_domain_mapping?: Array<ApplicationDomainMapping['Read']>;
		application__has__build_var_name?: Array<BuildEnvironmentVariable['Read']>;
		build_environment_variable?: Array<BuildEnvironmentVariable['Read']>;
		owns__device?: Array<Device['Read']>;
		owns__release?: Array<Release['Read']>;
		owns__public_device?: Array<PublicDevice['Read']>;
		team__grants_access_to__application?: Array<TeamApplicationAccess['Read']>;
		team_application_access?: Array<TeamApplicationAccess['Read']>;
		is_accessible_by__team?: Array<TeamApplicationAccess['Read']>;
		user__is_member_of__application?: Array<UserIsMemberOfApplication['Read']>;
		user_application_membership?: Array<UserIsMemberOfApplication['Read']>;
		includes__user?: Array<UserIsMemberOfApplication['Read']>;
		includes__user__is_member_of__application?: Array<
			UserIsMemberOfApplication['Read']
		>;
		includes__user_application_membership?: Array<
			UserIsMemberOfApplication['Read']
		>;
		invitee__is_invited_to__application?: Array<
			InviteeIsInvitedToApplication['Read']
		>;
		application_invite?: Array<InviteeIsInvitedToApplication['Read']>;
		invitee?: Array<InviteeIsInvitedToApplication['Read']>;
		is_directly_accessible_by__user?: Array<
			UserHasDirectAccessToApplication['Read']
		>;
		can_use__application_as_host?: Array<
			ApplicationCanUseApplicationAsHost['Read']
		>;
	};
	Write: {
		should_track_latest_release: Types['Boolean']['Write'];
		is_of__class: 'fleet' | 'block' | 'app';
		organization: Types['Integer']['Write'];
		app_name: Types['Text']['Write'];
		slug: Types['Short Text']['Write'];
		is_for__device_type: Types['Integer']['Write'];
		should_be_running__release: Types['Integer']['Write'] | null;
		application_type: Types['Integer']['Write'];
		is_archived: Types['Boolean']['Write'];
		uuid: Types['Text']['Write'];
		is_public: Types['Boolean']['Write'];
		is_accessible_by_support_until__date: Types['Date Time']['Write'] | null;
		is_stored_at__repository_url: Types['Text']['Write'] | null;
	};
}

export interface ApplicationEnvironmentVariable {
	Read: {
		created_at: Types['Date Time']['Read'];
		application: { __id: Application['Read']['id'] } | [Application['Read']];
		name: Types['Short Text']['Read'];
		id: Types['Integer']['Read'];
		value: Types['Text']['Read'];
	};
	Write: {
		application: Types['Integer']['Write'];
		name: Types['Short Text']['Write'];
		value: Types['Text']['Write'];
	};
}

export interface ApplicationConfigVariable {
	Read: {
		application: { __id: Application['Read']['id'] } | [Application['Read']];
		name: Types['Short Text']['Read'];
		id: Types['Integer']['Read'];
		value: Types['Text']['Read'];
	};
	Write: {
		application: Types['Integer']['Write'];
		name: Types['Short Text']['Write'];
		value: Types['Text']['Write'];
	};
}

export interface Service {
	Read: {
		created_at: Types['Date Time']['Read'];
		application: { __id: Application['Read']['id'] } | [Application['Read']];
		service_name: Types['Short Text']['Read'];
		id: Types['Integer']['Read'];
		application__has__service_name__has__label_name?: Array<
			ServiceLabel['Read']
		>;
		service__has__label_name?: Array<ServiceLabel['Read']>;
		service_label?: Array<ServiceLabel['Read']>;
		application__has__service_name__has__name?: Array<
			ServiceEnvironmentVariable['Read']
		>;
		service__has__name?: Array<ServiceEnvironmentVariable['Read']>;
		service_environment_variable?: Array<ServiceEnvironmentVariable['Read']>;
		device__installs__application__has__service_name?: Array<
			ServiceInstall['Read']
		>;
		device__installs__service?: Array<ServiceInstall['Read']>;
		service_install?: Array<ServiceInstall['Read']>;
		is_built_by__image?: Array<Image['Read']>;
	};
	Write: {
		application: Types['Integer']['Write'];
		service_name: Types['Short Text']['Write'];
	};
}

export interface ServiceLabel {
	Read: {
		created_at: Types['Date Time']['Read'];
		service: { __id: Service['Read']['id'] } | [Service['Read']];
		label_name: Types['Short Text']['Read'];
		id: Types['Integer']['Read'];
		value: Types['Text']['Read'];
		application__has__service_name:
			| { __id: Service['Read']['id'] }
			| [Service['Read']];
	};
	Write: {
		service: Types['Integer']['Write'];
		label_name: Types['Short Text']['Write'];
		value: Types['Text']['Write'];
	};
}

export interface ServiceEnvironmentVariable {
	Read: {
		created_at: Types['Date Time']['Read'];
		service: { __id: Service['Read']['id'] } | [Service['Read']];
		name: Types['Short Text']['Read'];
		id: Types['Integer']['Read'];
		value: Types['Text']['Read'];
		application__has__service_name:
			| { __id: Service['Read']['id'] }
			| [Service['Read']];
	};
	Write: {
		service: Types['Integer']['Write'];
		name: Types['Short Text']['Write'];
		value: Types['Text']['Write'];
	};
}

export interface ApplicationTag {
	Read: {
		application: { __id: Application['Read']['id'] } | [Application['Read']];
		tag_key: Types['Short Text']['Read'];
		id: Types['Integer']['Read'];
		value: Types['Text']['Read'];
	};
	Write: {
		application: Types['Integer']['Write'];
		tag_key: Types['Short Text']['Write'];
		value: Types['Text']['Write'];
	};
}

export interface Device {
	Read: {
		created_at: Types['Date Time']['Read'];
		modified_at: Types['Date Time']['Read'];
		id: Types['Integer']['Read'];
		actor: { __id: Actor['Read']['id'] } | [Actor['Read']];
		api_heartbeat_state: 'online' | 'offline' | 'timeout' | 'unknown';
		changed_api_heartbeat_state_on__date: Types['Date Time']['Read'] | null;
		uuid: Types['Text']['Read'];
		local_id: Types['Short Text']['Read'] | null;
		device_name: Types['Short Text']['Read'];
		note: Types['Text']['Read'] | null;
		is_of__device_type:
			| { __id: DeviceType['Read']['id'] }
			| [DeviceType['Read']];
		belongs_to__application:
			| { __id: Application['Read']['id'] }
			| [Application['Read']]
			| []
			| null;
		is_online: Types['Boolean']['Read'];
		last_connectivity_event: Types['Date Time']['Read'] | null;
		is_connected_to_vpn: Types['Boolean']['Read'];
		last_vpn_event: Types['Date Time']['Read'] | null;
		is_locked_until__date: Types['Date Time']['Read'] | null;
		public_address: Types['Short Text']['Read'] | null;
		ip_address: Types['Short Text']['Read'] | null;
		mac_address: Types['Short Text']['Read'] | null;
		is_web_accessible: Types['Boolean']['Read'];
		memory_usage: Types['Integer']['Read'] | null;
		memory_total: Types['Integer']['Read'] | null;
		storage_block_device: Types['Short Text']['Read'] | null;
		storage_usage: Types['Integer']['Read'] | null;
		storage_total: Types['Integer']['Read'] | null;
		cpu_usage: Types['Integer']['Read'] | null;
		cpu_temp: Types['Integer']['Read'] | null;
		is_undervolted: Types['Boolean']['Read'];
		cpu_id: Types['Short Text']['Read'] | null;
		is_running__release:
			| { __id: Release['Read']['id'] }
			| [Release['Read']]
			| []
			| null;
		download_progress: Types['Integer']['Read'] | null;
		status: Types['Short Text']['Read'] | null;
		os_version: Types['Short Text']['Read'] | null;
		os_variant: Types['Short Text']['Read'] | null;
		overall_status: Types['Short Text']['Read'];
		overall_progress: Types['Integer']['Read'] | null;
		supervisor_version: Types['Short Text']['Read'] | null;
		provisioning_progress: Types['Integer']['Read'] | null;
		provisioning_state: Types['Short Text']['Read'] | null;
		is_managed_by__service_instance:
			| { __id: ServiceInstance['Read']['id'] }
			| [ServiceInstance['Read']]
			| []
			| null;
		is_pinned_on__release:
			| { __id: Release['Read']['id'] }
			| [Release['Read']]
			| []
			| null;
		should_be_running__release:
			| { __id: Release['Read']['id'] }
			| [Release['Read']]
			| []
			| null;
		should_be_operated_by__release:
			| { __id: Release['Read']['id'] }
			| [Release['Read']]
			| []
			| null;
		should_be_managed_by__release:
			| { __id: Release['Read']['id'] }
			| [Release['Read']]
			| []
			| null;
		update_status:
			| 'rejected'
			| 'downloading'
			| 'downloaded'
			| 'applying changes'
			| 'aborted'
			| 'done'
			| null;
		last_update_status_event: Types['Date Time']['Read'] | null;
		belongs_to__user: { __id: User['Read']['id'] } | [User['Read']] | [] | null;
		latitude: Types['Short Text']['Read'] | null;
		longitude: Types['Short Text']['Read'] | null;
		custom_latitude: Types['Short Text']['Read'] | null;
		custom_longitude: Types['Short Text']['Read'] | null;
		location: Types['Text']['Read'] | null;
		is_accessible_by_support_until__date: Types['Date Time']['Read'] | null;
		is_active: Types['Boolean']['Read'];
		is_frozen: Types['Boolean']['Read'];
		device__has__env_var_name?: Array<DeviceEnvironmentVariable['Read']>;
		device_environment_variable?: Array<DeviceEnvironmentVariable['Read']>;
		device__has__config_var_name?: Array<DeviceConfigVariable['Read']>;
		device_config_variable?: Array<DeviceConfigVariable['Read']>;
		device__has__tag_key?: Array<DeviceTag['Read']>;
		device_tag?: Array<DeviceTag['Read']>;
		device__has__fqdn?: Array<DeviceDomainMapping['Read']>;
		device_domain_mapping?: Array<DeviceDomainMapping['Read']>;
		device__installs__image?: Array<ImageInstall['Read']>;
		image_install?: Array<ImageInstall['Read']>;
		device__installs__application__has__service_name?: Array<
			ServiceInstall['Read']
		>;
		device__installs__service?: Array<ServiceInstall['Read']>;
		service_install?: Array<ServiceInstall['Read']>;
		installs__image?: Array<ImageInstall['Read']>;
		installs__application__has__service_name?: Array<ServiceInstall['Read']>;
		installs__service?: Array<ServiceInstall['Read']>;
	};
	Write: {
		uuid: Types['Text']['Write'];
		local_id: Types['Short Text']['Write'] | null;
		device_name: Types['Short Text']['Write'];
		note: Types['Text']['Write'] | null;
		is_of__device_type: Types['Integer']['Write'];
		belongs_to__application: Types['Integer']['Write'] | null;
		is_online: Types['Boolean']['Write'];
		last_connectivity_event: Types['Date Time']['Write'] | null;
		is_locked_until__date: Types['Date Time']['Write'] | null;
		public_address: Types['Short Text']['Write'] | null;
		ip_address: Types['Short Text']['Write'] | null;
		mac_address: Types['Short Text']['Write'] | null;
		is_web_accessible: Types['Boolean']['Write'];
		memory_usage: Types['Integer']['Write'] | null;
		memory_total: Types['Integer']['Write'] | null;
		storage_block_device: Types['Short Text']['Write'] | null;
		storage_usage: Types['Integer']['Write'] | null;
		storage_total: Types['Integer']['Write'] | null;
		cpu_usage: Types['Integer']['Write'] | null;
		cpu_temp: Types['Integer']['Write'] | null;
		is_undervolted: Types['Boolean']['Write'];
		cpu_id: Types['Short Text']['Write'] | null;
		is_running__release: Types['Integer']['Write'] | null;
		download_progress: Types['Integer']['Write'] | null;
		status: Types['Short Text']['Write'] | null;
		os_version: Types['Short Text']['Write'] | null;
		os_variant: Types['Short Text']['Write'] | null;
		supervisor_version: Types['Short Text']['Write'] | null;
		provisioning_progress: Types['Integer']['Write'] | null;
		provisioning_state: Types['Short Text']['Write'] | null;
		is_managed_by__service_instance: Types['Integer']['Write'] | null;
		is_pinned_on__release: Types['Integer']['Write'] | null;
		should_be_operated_by__release: Types['Integer']['Write'] | null;
		should_be_managed_by__release: Types['Integer']['Write'] | null;
		update_status:
			| 'rejected'
			| 'downloading'
			| 'downloaded'
			| 'applying changes'
			| 'aborted'
			| 'done'
			| null;
		last_update_status_event: Types['Date Time']['Write'] | null;
		belongs_to__user: Types['Integer']['Write'] | null;
		custom_latitude: Types['Short Text']['Write'] | null;
		custom_longitude: Types['Short Text']['Write'] | null;
		is_accessible_by_support_until__date: Types['Date Time']['Write'] | null;
		is_active: Types['Boolean']['Write'];
	};
}

export interface DeviceEnvironmentVariable {
	Read: {
		created_at: Types['Date Time']['Read'];
		device: { __id: Device['Read']['id'] } | [Device['Read']];
		name: Types['Short Text']['Read'];
		id: Types['Integer']['Read'];
		value: Types['Text']['Read'];
	};
	Write: {
		device: Types['Integer']['Write'];
		name: Types['Short Text']['Write'];
		value: Types['Text']['Write'];
	};
}

export interface DeviceConfigVariable {
	Read: {
		device: { __id: Device['Read']['id'] } | [Device['Read']];
		name: Types['Short Text']['Read'];
		id: Types['Integer']['Read'];
		value: Types['Text']['Read'];
	};
	Write: {
		device: Types['Integer']['Write'];
		name: Types['Short Text']['Write'];
		value: Types['Text']['Write'];
	};
}

export interface ImageInstall {
	Read: {
		device: { __id: Device['Read']['id'] } | [Device['Read']];
		installs__image: { __id: Image['Read']['id'] } | [Image['Read']];
		id: Types['Integer']['Read'];
		install_date: Types['Date Time']['Read'];
		download_progress: Types['Integer']['Read'] | null;
		status: Types['Short Text']['Read'];
		is_provided_by__release:
			| { __id: Release['Read']['id'] }
			| [Release['Read']];
		image: { __id: Image['Read']['id'] } | [Image['Read']];
	};
	Write: {
		device: Types['Integer']['Write'];
		installs__image: Types['Integer']['Write'];
		install_date: Types['Date Time']['Write'];
		download_progress: Types['Integer']['Write'] | null;
		status: Types['Short Text']['Write'];
		is_provided_by__release: Types['Integer']['Write'];
	};
}

export interface ServiceInstall {
	Read: {
		created_at: Types['Date Time']['Read'];
		device: { __id: Device['Read']['id'] } | [Device['Read']];
		installs__service: { __id: Service['Read']['id'] } | [Service['Read']];
		id: Types['Integer']['Read'];
		device__installs__application__has__service_name__has__name?: Array<
			DeviceServiceEnvironmentVariable['Read']
		>;
		device__installs__service__has__name?: Array<
			DeviceServiceEnvironmentVariable['Read']
		>;
		device__installs__service_environment_variable?: Array<
			DeviceServiceEnvironmentVariable['Read']
		>;
		service_install__has__name?: Array<
			DeviceServiceEnvironmentVariable['Read']
		>;
		device_service_environment_variable?: Array<
			DeviceServiceEnvironmentVariable['Read']
		>;
		application__has__service_name:
			| { __id: Service['Read']['id'] }
			| [Service['Read']];
		service: { __id: Service['Read']['id'] } | [Service['Read']];
		installs__application__has__service_name:
			| { __id: Service['Read']['id'] }
			| [Service['Read']];
	};
	Write: {
		device: Types['Integer']['Write'];
		installs__service: Types['Integer']['Write'];
	};
}

export interface DeviceServiceEnvironmentVariable {
	Read: {
		created_at: Types['Date Time']['Read'];
		service_install:
			| { __id: ServiceInstall['Read']['id'] }
			| [ServiceInstall['Read']];
		name: Types['Short Text']['Read'];
		id: Types['Integer']['Read'];
		value: Types['Text']['Read'];
		device__installs__application__has__service_name:
			| { __id: ServiceInstall['Read']['id'] }
			| [ServiceInstall['Read']];
		device__installs__service:
			| { __id: ServiceInstall['Read']['id'] }
			| [ServiceInstall['Read']];
	};
	Write: {
		service_install: Types['Integer']['Write'];
		name: Types['Short Text']['Write'];
		value: Types['Text']['Write'];
	};
}

export interface DeviceTag {
	Read: {
		device: { __id: Device['Read']['id'] } | [Device['Read']];
		tag_key: Types['Short Text']['Read'];
		id: Types['Integer']['Read'];
		value: Types['Text']['Read'];
	};
	Write: {
		device: Types['Integer']['Write'];
		tag_key: Types['Short Text']['Write'];
		value: Types['Text']['Write'];
	};
}

export interface Release {
	Read: {
		created_at: Types['Date Time']['Read'];
		id: Types['Integer']['Read'];
		belongs_to__application:
			| { __id: Application['Read']['id'] }
			| [Application['Read']];
		commit: Types['Short Text']['Read'];
		composition: Types['JSON']['Read'];
		status: Types['Short Text']['Read'];
		source: Types['Short Text']['Read'];
		build_log: Types['Text']['Read'] | null;
		is_invalidated: Types['Boolean']['Read'];
		start_timestamp: Types['Date Time']['Read'];
		end_timestamp: Types['Date Time']['Read'] | null;
		update_timestamp: Types['Date Time']['Read'];
		release_version: Types['Short Text']['Read'] | null;
		contract: Types['JSON']['Read'] | null;
		is_passing_tests: Types['Boolean']['Read'];
		is_finalized_at__date: Types['Date Time']['Read'] | null;
		phase: 'next' | 'current' | 'sunset' | 'end-of-life' | null;
		is_final: Types['Boolean']['Read'];
		semver: Types['Short Text']['Read'];
		semver_major: Types['Integer']['Read'];
		semver_minor: Types['Integer']['Read'];
		semver_patch: Types['Integer']['Read'];
		semver_prerelease: Types['Short Text']['Read'];
		semver_build: Types['Short Text']['Read'];
		variant: Types['Short Text']['Read'];
		revision: Types['Integer']['Read'] | null;
		raw_version: Types['Short Text']['Read'];
		version: Types['JSON']['Read'];
		known_issue_list: Types['Text']['Read'] | null;
		note: Types['Text']['Read'] | null;
		invalidation_reason: Types['Text']['Read'] | null;
		is_created_by__user:
			| { __id: User['Read']['id'] }
			| [User['Read']]
			| []
			| null;
		release__has__tag_key?: Array<ReleaseTag['Read']>;
		release_tag?: Array<ReleaseTag['Read']>;
		release__has__asset_key?: Array<ReleaseAsset['Read']>;
		release_asset?: Array<ReleaseAsset['Read']>;
		image__is_part_of__release?: Array<ImageIsPartOfRelease['Read']>;
		release_image?: Array<ImageIsPartOfRelease['Read']>;
		contains__image?: Array<ImageIsPartOfRelease['Read']>;
		should_be_running_on__application?: Array<Application['Read']>;
		should_be_running_on__device?: Array<Device['Read']>;
		is_running_on__device?: Array<Device['Read']>;
		is_pinned_to__device?: Array<Device['Read']>;
		should_operate__device?: Array<Device['Read']>;
		should_manage__device?: Array<Device['Read']>;
		provides__device__installs__image?: Array<ImageInstall['Read']>;
		provides__image_install?: Array<ImageInstall['Read']>;
	};
	Write: {
		belongs_to__application: Types['Integer']['Write'];
		commit: Types['Short Text']['Write'];
		composition: Types['JSON']['Write'];
		status: Types['Short Text']['Write'];
		source: Types['Short Text']['Write'];
		build_log: Types['Text']['Write'] | null;
		is_invalidated: Types['Boolean']['Write'];
		start_timestamp: Types['Date Time']['Write'];
		end_timestamp: Types['Date Time']['Write'] | null;
		update_timestamp: Types['Date Time']['Write'];
		release_version: Types['Short Text']['Write'] | null;
		contract: Types['JSON']['Write'] | null;
		is_passing_tests: Types['Boolean']['Write'];
		phase: 'next' | 'current' | 'sunset' | 'end-of-life' | null;
		is_final: Types['Boolean']['Write'];
		semver: Types['Short Text']['Write'];
		semver_major: Types['Integer']['Write'];
		semver_minor: Types['Integer']['Write'];
		semver_patch: Types['Integer']['Write'];
		semver_prerelease: Types['Short Text']['Write'];
		semver_build: Types['Short Text']['Write'];
		variant: Types['Short Text']['Write'];
		known_issue_list: Types['Text']['Write'] | null;
		note: Types['Text']['Write'] | null;
		invalidation_reason: Types['Text']['Write'] | null;
		is_created_by__user: Types['Integer']['Write'] | null;
	};
}

export interface ReleaseTag {
	Read: {
		release: { __id: Release['Read']['id'] } | [Release['Read']];
		tag_key: Types['Short Text']['Read'];
		id: Types['Integer']['Read'];
		value: Types['Text']['Read'];
	};
	Write: {
		release: Types['Integer']['Write'];
		tag_key: Types['Short Text']['Write'];
		value: Types['Text']['Write'];
	};
}

export interface ImageIsPartOfRelease {
	Read: {
		created_at: Types['Date Time']['Read'];
		image: { __id: Image['Read']['id'] } | [Image['Read']];
		is_part_of__release: { __id: Release['Read']['id'] } | [Release['Read']];
		id: Types['Integer']['Read'];
		image__is_part_of__release__has__label_name?: Array<ImageLabel['Read']>;
		release_image__has__label_name?: Array<ImageLabel['Read']>;
		image_label?: Array<ImageLabel['Read']>;
		image__is_part_of__release__has__name?: Array<
			ImageEnvironmentVariable['Read']
		>;
		release_image__has__name?: Array<ImageEnvironmentVariable['Read']>;
		image_environment_variable?: Array<ImageEnvironmentVariable['Read']>;
		release: { __id: Release['Read']['id'] } | [Release['Read']];
		contains__image: { __id: Image['Read']['id'] } | [Image['Read']];
	};
	Write: {
		image: Types['Integer']['Write'];
		is_part_of__release: Types['Integer']['Write'];
	};
}

export interface ImageLabel {
	Read: {
		created_at: Types['Date Time']['Read'];
		release_image:
			| { __id: ImageIsPartOfRelease['Read']['id'] }
			| [ImageIsPartOfRelease['Read']];
		label_name: Types['Short Text']['Read'];
		id: Types['Integer']['Read'];
		value: Types['Text']['Read'];
		image__is_part_of__release:
			| { __id: ImageIsPartOfRelease['Read']['id'] }
			| [ImageIsPartOfRelease['Read']];
	};
	Write: {
		release_image: Types['Integer']['Write'];
		label_name: Types['Short Text']['Write'];
		value: Types['Text']['Write'];
	};
}

export interface ImageEnvironmentVariable {
	Read: {
		created_at: Types['Date Time']['Read'];
		release_image:
			| { __id: ImageIsPartOfRelease['Read']['id'] }
			| [ImageIsPartOfRelease['Read']];
		name: Types['Short Text']['Read'];
		id: Types['Integer']['Read'];
		value: Types['Text']['Read'];
		image__is_part_of__release:
			| { __id: ImageIsPartOfRelease['Read']['id'] }
			| [ImageIsPartOfRelease['Read']];
	};
	Write: {
		release_image: Types['Integer']['Write'];
		name: Types['Short Text']['Write'];
		value: Types['Text']['Write'];
	};
}

export interface OrganizationMembership {
	Read: {
		created_at: Types['Date Time']['Read'];
		user: { __id: User['Read']['id'] } | [User['Read']];
		is_member_of__organization:
			| { __id: Organization['Read']['id'] }
			| [Organization['Read']];
		id: Types['Integer']['Read'];
		organization_membership_role:
			| { __id: OrganizationMembershipRole['Read']['id'] }
			| [OrganizationMembershipRole['Read']];
		effective_seat_role: Types['Short Text']['Read'];
		user__is_member_of__organization__has__tag_key?: Array<
			OrganizationMembershipTag['Read']
		>;
		organization_membership__has__tag_key?: Array<
			OrganizationMembershipTag['Read']
		>;
		organization_membership_tag?: Array<OrganizationMembershipTag['Read']>;
		organization: { __id: Organization['Read']['id'] } | [Organization['Read']];
		includes__user: { __id: User['Read']['id'] } | [User['Read']];
	};
	Write: {
		user: Types['Integer']['Write'];
		is_member_of__organization: Types['Integer']['Write'];
		organization_membership_role: Types['Integer']['Write'];
	};
}

export interface UserHasPublicKey {
	Read: {
		created_at: Types['Date Time']['Read'];
		user: { __id: User['Read']['id'] } | [User['Read']];
		public_key: Types['Text']['Read'];
		id: Types['Integer']['Read'];
		title: Types['Short Text']['Read'];
	};
	Write: {
		user: Types['Integer']['Write'];
		public_key: Types['Text']['Write'];
		title: Types['Short Text']['Write'];
	};
}

export interface DeviceTypeAlias {
	Read: {
		device_type: { __id: DeviceType['Read']['id'] } | [DeviceType['Read']];
		is_referenced_by__alias: Types['Short Text']['Read'];
		id: Types['Integer']['Read'];
	};
	Write: Record<string, never>;
}

export interface ReleaseAsset {
	Read: {
		release: { __id: Release['Read']['id'] } | [Release['Read']];
		asset_key: Types['Short Text']['Read'];
		id: Types['Integer']['Read'];
		asset: Types['WebResource']['Read'] | null;
	};
	Write: {
		release: Types['Integer']['Write'];
		asset_key: Types['Short Text']['Write'];
		asset: Types['WebResource']['Write'] | null;
	};
}

export interface ApplicationMembershipRole {
	Read: {
		id: Types['Integer']['Read'];
		name: Types['Short Text']['Read'];
		is_of__team__grants_access_to__application?: Array<
			TeamApplicationAccess['Read']
		>;
		is_of__team_application_access?: Array<TeamApplicationAccess['Read']>;
		is_of__invitee__is_invited_to__application?: Array<
			InviteeIsInvitedToApplication['Read']
		>;
		is_of__application_invite?: Array<InviteeIsInvitedToApplication['Read']>;
		is_of__user__is_member_of__application?: Array<
			UserIsMemberOfApplication['Read']
		>;
		is_of__user_application_membership?: Array<
			UserIsMemberOfApplication['Read']
		>;
	};
	Write: Record<string, never>;
}

export interface CreditBundle {
	Read: {
		created_at: Types['Date Time']['Read'];
		modified_at: Types['Date Time']['Read'];
		id: Types['Integer']['Read'];
		payment_status:
			| 'processing'
			| 'paid'
			| 'failed'
			| 'complimentary'
			| 'cancelled'
			| 'refunded'
			| 'manually invoiced';
		is_created_by__user: { __id: User['Read']['id'] } | [User['Read']];
		is_for__feature: { __id: Feature['Read']['id'] } | [Feature['Read']];
		belongs_to__organization:
			| { __id: Organization['Read']['id'] }
			| [Organization['Read']];
		unit_cost: Types['Integer']['Read'];
		original_quantity: Types['Integer']['Read'];
		available_balance: Types['Integer']['Read'];
		total_cost: Types['Integer']['Read'];
		total_balance: Types['Integer']['Read'];
		expires_on__date: Types['Date Time']['Read'];
		is_associated_with__invoice_id: Types['Short Text']['Read'] | null;
		error_message: Types['Text']['Read'] | null;
	};
	Write: {
		is_for__feature: Types['Integer']['Write'];
		belongs_to__organization: Types['Integer']['Write'];
		original_quantity: Types['Integer']['Write'];
	};
}

export interface Delta {
	Read: {
		created_at: Types['Date Time']['Read'];
		id: Types['Integer']['Read'];
		originates_from__image:
			| { __id: Image['Read']['id'] }
			| [Image['Read']]
			| []
			| null;
		produces__image: { __id: Image['Read']['id'] } | [Image['Read']];
		version: Types['Integer']['Read'];
		status: Types['Short Text']['Read'];
		error_message: Types['Text']['Read'] | null;
		is_stored_at__location: Types['Text']['Read'] | null;
		size: Types['Big Integer']['Read'] | null;
		update_timestamp: Types['Date Time']['Read'];
		end_timestamp: Types['Date Time']['Read'] | null;
	};
	Write: {
		created_at: Types['Date Time']['Write'];
		originates_from__image: Types['Integer']['Write'] | null;
		produces__image: Types['Integer']['Write'];
		version: Types['Integer']['Write'];
		status: Types['Short Text']['Write'];
		error_message: Types['Text']['Write'] | null;
		is_stored_at__location: Types['Text']['Write'] | null;
		size: Types['Big Integer']['Write'] | null;
		update_timestamp: Types['Date Time']['Write'];
		end_timestamp: Types['Date Time']['Write'] | null;
	};
}

export interface Feature {
	Read: {
		id: Types['Integer']['Read'];
		title: Types['Short Text']['Read'];
		slug: Types['Short Text']['Read'];
		billing_code: Types['Short Text']['Read'] | null;
		is_of__support_feature?: Array<SupportFeature['Read']>;
		organization__owns_credit_notification_for__feature?: Array<
			OrganizationCreditNotification['Read']
		>;
		organization_credit_notification?: Array<
			OrganizationCreditNotification['Read']
		>;
		plan__provides__feature?: Array<PlanFeature['Read']>;
		plan_feature?: Array<PlanFeature['Read']>;
		plan__offers__feature?: Array<PlanAddon['Read']>;
		plan_addon?: Array<PlanAddon['Read']>;
		is_offered_by__plan?: Array<PlanAddon['Read']>;
	};
	Write: Record<string, never>;
}

export interface OauthApplication {
	Read: {
		id: Types['Integer']['Read'];
		name: Types['Short Text']['Read'];
		client_id: Types['Short Text']['Read'];
		redirect_uri: Types['Short Text']['Read'];
		description: Types['Text']['Read'] | null;
		oauth_application_authorization?: Array<
			OauthApplicationAuthorization['Read']
		>;
	};
	Write: Record<string, never>;
}

export interface OauthApplicationAuthorization {
	Read: {
		id: Types['Integer']['Read'];
		belongs_to__user: { __id: User['Read']['id'] } | [User['Read']];
		is_for__oauth_application:
			| { __id: OauthApplication['Read']['id'] }
			| [OauthApplication['Read']];
	};
	Write: {
		id: Types['Integer']['Write'];
		belongs_to__user: Types['Integer']['Write'];
		is_for__oauth_application: Types['Integer']['Write'];
	};
}

export interface OrganizationMembershipRole {
	Read: {
		id: Types['Integer']['Read'];
		name: Types['Short Text']['Read'];
		is_of__user__is_member_of__organization?: Array<
			OrganizationMembership['Read']
		>;
		is_of__organization_membership?: Array<OrganizationMembership['Read']>;
		is_of__invitee__is_invited_to__organization?: Array<
			InviteeIsInvitedToOrganization['Read']
		>;
		is_of__organization_invite?: Array<InviteeIsInvitedToOrganization['Read']>;
	};
	Write: Record<string, never>;
}

export interface Plan {
	Read: {
		id: Types['Integer']['Read'];
		title: Types['Short Text']['Read'];
		billing_code: Types['Short Text']['Read'] | null;
		monthly_price: Types['Integer']['Read'];
		annual_price: Types['Integer']['Read'];
		can_self_serve: Types['Boolean']['Read'];
		is_legacy: Types['Boolean']['Read'];
		is_valid_from__date: Types['Date Time']['Read'] | null;
		is_valid_until__date: Types['Date Time']['Read'] | null;
		plan__has__discount_code?: Array<PlanHasDiscountCode['Read']>;
		plan__provides__feature?: Array<PlanFeature['Read']>;
		plan_feature?: Array<PlanFeature['Read']>;
		plan__offers__feature?: Array<PlanAddon['Read']>;
		plan_addon?: Array<PlanAddon['Read']>;
		provides__feature?: Array<PlanFeature['Read']>;
		offers__feature?: Array<PlanAddon['Read']>;
		offers__plan__offers__feature?: Array<PlanAddon['Read']>;
		offers__plan_addon?: Array<PlanAddon['Read']>;
		is_of__plan__offers__feature?: Array<PlanAddon['Read']>;
		is_of__plan_addon?: Array<PlanAddon['Read']>;
		subscription?: Array<Subscription['Read']>;
	};
	Write: Record<string, never>;
}

export interface RecoveryTwoFactor {
	Read: {
		id: Types['Integer']['Read'];
		used_timestamp: Types['Date Time']['Read'] | null;
		belongs_to__user: { __id: User['Read']['id'] } | [User['Read']];
	};
	Write: Record<string, never>;
}

export interface SocialServiceAccount {
	Read: {
		belongs_to__user: { __id: User['Read']['id'] } | [User['Read']];
		provider: Types['Short Text']['Read'];
		display_name: Types['Short Text']['Read'] | null;
	};
	Write: Record<string, never>;
}

export interface Subscription {
	Read: {
		id: Types['Integer']['Read'];
		is_for__plan: { __id: Plan['Read']['id'] } | [Plan['Read']];
		is_for__organization:
			| { __id: Organization['Read']['id'] }
			| [Organization['Read']];
		billing_cycle: Types['Short Text']['Read'];
		starts_on__date: Types['Date Time']['Read'];
		ends_on__date: Types['Date Time']['Read'] | null;
		is_active: Types['Boolean']['Read'];
		discount_percentage: Types['Real']['Read'];
		origin: Types['Short Text']['Read'];
		subscription__discounts__plan__offers__feature?: Array<
			SubscriptionDiscountsPlanAddon['Read']
		>;
		subscription__discounts__plan_addon?: Array<
			SubscriptionDiscountsPlanAddon['Read']
		>;
		subscription_addon_discount?: Array<SubscriptionDiscountsPlanAddon['Read']>;
		discounts__plan__offers__feature?: Array<
			SubscriptionDiscountsPlanAddon['Read']
		>;
		discounts__plan_addon?: Array<SubscriptionDiscountsPlanAddon['Read']>;
		subscription_prepaid_addon?: Array<SubscriptionPrepaidAddon['Read']>;
	};
	Write: {
		is_for__plan: Types['Integer']['Write'];
		is_for__organization: Types['Integer']['Write'];
		billing_cycle: Types['Short Text']['Write'];
		starts_on__date: Types['Date Time']['Write'];
		ends_on__date: Types['Date Time']['Write'] | null;
		discount_percentage: Types['Real']['Write'];
		origin: Types['Short Text']['Write'];
	};
}

export interface SubscriptionPrepaidAddon {
	Read: {
		id: Types['Integer']['Read'];
		is_for__subscription:
			| { __id: Subscription['Read']['id'] }
			| [Subscription['Read']];
		is_for__plan_addon: { __id: PlanAddon['Read']['id'] } | [PlanAddon['Read']];
		discount_percentage: Types['Real']['Read'];
		quantity: Types['Integer']['Read'];
		starts_on__date: Types['Date Time']['Read'];
		expires_on__date: Types['Date Time']['Read'] | null;
		is_for__plan__offers__feature:
			| { __id: PlanAddon['Read']['id'] }
			| [PlanAddon['Read']];
	};
	Write: Record<string, never>;
}

export interface SupportTier {
	Read: {
		id: Types['Integer']['Read'];
		title: Types['Short Text']['Read'];
		slug: Types['Short Text']['Read'];
		includes_private_support: Types['Boolean']['Read'];
		includes__SLA: Types['Short Text']['Read'] | null;
		is_of__support_feature?: Array<SupportFeature['Read']>;
	};
	Write: Record<string, never>;
}

export interface Team {
	Read: {
		created_at: Types['Date Time']['Read'];
		id: Types['Integer']['Read'];
		belongs_to__organization:
			| { __id: Organization['Read']['id'] }
			| [Organization['Read']];
		name: Types['Short Text']['Read'];
		description: Types['Text']['Read'] | null;
		team__grants_access_to__application?: Array<TeamApplicationAccess['Read']>;
		team_application_access?: Array<TeamApplicationAccess['Read']>;
		grants_access_to__application?: Array<TeamApplicationAccess['Read']>;
		user__is_member_of__team?: Array<TeamMembership['Read']>;
		team_membership?: Array<TeamMembership['Read']>;
		includes__user?: Array<TeamMembership['Read']>;
	};
	Write: {
		belongs_to__organization: Types['Integer']['Write'];
		name: Types['Short Text']['Write'];
		description: Types['Text']['Write'] | null;
	};
}

export interface Invitee {
	Read: {
		id: Types['Integer']['Read'];
		email: Types['Text']['Read'];
		is_invited_to__application?: Array<InviteeIsInvitedToApplication['Read']>;
		is_invited_to__organization?: Array<InviteeIsInvitedToOrganization['Read']>;
		invitee__is_invited_to__application?: Array<
			InviteeIsInvitedToApplication['Read']
		>;
		application_invite?: Array<InviteeIsInvitedToApplication['Read']>;
		invitee__is_invited_to__organization?: Array<
			InviteeIsInvitedToOrganization['Read']
		>;
		organization_invite?: Array<InviteeIsInvitedToOrganization['Read']>;
		is_of__invitee__is_invited_to__application?: Array<
			InviteeIsInvitedToApplication['Read']
		>;
		is_of__application_invite?: Array<InviteeIsInvitedToApplication['Read']>;
		is_of__invitee__is_invited_to__organization?: Array<
			InviteeIsInvitedToOrganization['Read']
		>;
		is_of__organization_invite?: Array<InviteeIsInvitedToOrganization['Read']>;
		includes__invitee__is_invited_to__application?: Array<
			InviteeIsInvitedToApplication['Read']
		>;
		includes__application_invite?: Array<InviteeIsInvitedToApplication['Read']>;
		includes__invitee__is_invited_to__organization?: Array<
			InviteeIsInvitedToOrganization['Read']
		>;
		includes__organization_invite?: Array<
			InviteeIsInvitedToOrganization['Read']
		>;
	};
	Write: {
		email: Types['Text']['Write'];
	};
}

export interface SupportFeature {
	Read: {
		id: Types['Integer']['Read'];
		feature: { __id: Feature['Read']['id'] } | [Feature['Read']];
		support_tier: { __id: SupportTier['Read']['id'] } | [SupportTier['Read']];
	};
	Write: Record<string, never>;
}

export interface TeamApplicationAccess {
	Read: {
		created_at: Types['Date Time']['Read'];
		team: { __id: Team['Read']['id'] } | [Team['Read']];
		grants_access_to__application:
			| { __id: Application['Read']['id'] }
			| [Application['Read']];
		id: Types['Integer']['Read'];
		application_membership_role:
			| { __id: ApplicationMembershipRole['Read']['id'] }
			| [ApplicationMembershipRole['Read']];
		application: { __id: Application['Read']['id'] } | [Application['Read']];
		is_accessible_by__team: { __id: Team['Read']['id'] } | [Team['Read']];
	};
	Write: {
		team: Types['Integer']['Write'];
		grants_access_to__application: Types['Integer']['Write'];
		application_membership_role: Types['Integer']['Write'];
	};
}

export interface TeamMembership {
	Read: {
		created_at: Types['Date Time']['Read'];
		user: { __id: User['Read']['id'] } | [User['Read']];
		is_member_of__team: { __id: Team['Read']['id'] } | [Team['Read']];
		id: Types['Integer']['Read'];
		team: { __id: Team['Read']['id'] } | [Team['Read']];
		includes__user: { __id: User['Read']['id'] } | [User['Read']];
	};
	Write: {
		user: Types['Integer']['Write'];
		is_member_of__team: Types['Integer']['Write'];
	};
}

export interface UserIsMemberOfApplication {
	Read: {
		user: { __id: User['Read']['id'] } | [User['Read']];
		is_member_of__application:
			| { __id: Application['Read']['id'] }
			| [Application['Read']];
		id: Types['Integer']['Read'];
		application_membership_role:
			| { __id: ApplicationMembershipRole['Read']['id'] }
			| [ApplicationMembershipRole['Read']];
		application: { __id: Application['Read']['id'] } | [Application['Read']];
		includes__user: { __id: User['Read']['id'] } | [User['Read']];
	};
	Write: {
		user: Types['Integer']['Write'];
		is_member_of__application: Types['Integer']['Write'];
		application_membership_role: Types['Integer']['Write'];
	};
}

export interface InviteeIsInvitedToApplication {
	Read: {
		invitee: { __id: Invitee['Read']['id'] } | [Invitee['Read']];
		is_invited_to__application:
			| { __id: Application['Read']['id'] }
			| [Application['Read']];
		id: Types['Integer']['Read'];
		application_membership_role:
			| { __id: ApplicationMembershipRole['Read']['id'] }
			| [ApplicationMembershipRole['Read']];
		message: Types['Text']['Read'] | null;
		is_created_by__user:
			| { __id: User['Read']['id'] }
			| [User['Read']]
			| []
			| null;
		application: { __id: Application['Read']['id'] } | [Application['Read']];
	};
	Write: {
		invitee: Types['Integer']['Write'];
		is_invited_to__application: Types['Integer']['Write'];
		application_membership_role: Types['Integer']['Write'];
		message: Types['Text']['Write'] | null;
	};
}

export interface InviteeIsInvitedToOrganization {
	Read: {
		invitee: { __id: Invitee['Read']['id'] } | [Invitee['Read']];
		is_invited_to__organization:
			| { __id: Organization['Read']['id'] }
			| [Organization['Read']];
		id: Types['Integer']['Read'];
		organization_membership_role:
			| { __id: OrganizationMembershipRole['Read']['id'] }
			| [OrganizationMembershipRole['Read']];
		message: Types['Text']['Read'] | null;
		is_created_by__user:
			| { __id: User['Read']['id'] }
			| [User['Read']]
			| []
			| null;
		organization: { __id: Organization['Read']['id'] } | [Organization['Read']];
	};
	Write: {
		invitee: Types['Integer']['Write'];
		is_invited_to__organization: Types['Integer']['Write'];
		organization_membership_role: Types['Integer']['Write'];
		message: Types['Text']['Write'] | null;
	};
}

export interface DeviceDomainMapping {
	Read: {
		created_at: Types['Date Time']['Read'];
		device: { __id: Device['Read']['id'] } | [Device['Read']];
		fqdn: Types['Text']['Read'];
		id: Types['Integer']['Read'];
	};
	Write: {
		device: Types['Integer']['Write'];
		fqdn: Types['Text']['Write'];
	};
}

export interface ApplicationDomainMapping {
	Read: {
		created_at: Types['Date Time']['Read'];
		application: { __id: Application['Read']['id'] } | [Application['Read']];
		domain: Types['Text']['Read'];
		id: Types['Integer']['Read'];
	};
	Write: {
		application: Types['Integer']['Write'];
		domain: Types['Text']['Write'];
	};
}

export interface BuildEnvironmentVariable {
	Read: {
		created_at: Types['Date Time']['Read'];
		application: { __id: Application['Read']['id'] } | [Application['Read']];
		name: Types['Short Text']['Read'];
		id: Types['Integer']['Read'];
		value: Types['Text']['Read'];
	};
	Write: {
		application: Types['Integer']['Write'];
		name: Types['Short Text']['Write'];
		value: Types['Text']['Write'];
	};
}

export interface OrganizationHasPrivateAccessToDeviceType {
	Read: {
		organization: { __id: Organization['Read']['id'] } | [Organization['Read']];
		has_private_access_to__device_type:
			| { __id: DeviceType['Read']['id'] }
			| [DeviceType['Read']];
		id: Types['Integer']['Read'];
		device_type: { __id: DeviceType['Read']['id'] } | [DeviceType['Read']];
		is_accessible_privately_by__organization:
			| { __id: Organization['Read']['id'] }
			| [Organization['Read']];
	};
	Write: Record<string, never>;
}

export interface OrganizationMembershipTag {
	Read: {
		organization_membership:
			| { __id: OrganizationMembership['Read']['id'] }
			| [OrganizationMembership['Read']];
		tag_key: Types['Short Text']['Read'];
		id: Types['Integer']['Read'];
		value: Types['Text']['Read'];
		user__is_member_of__organization:
			| { __id: OrganizationMembership['Read']['id'] }
			| [OrganizationMembership['Read']];
	};
	Write: {
		organization_membership: Types['Integer']['Write'];
		tag_key: Types['Short Text']['Write'];
		value: Types['Text']['Write'];
	};
}

export interface OrganizationCreditNotification {
	Read: {
		created_at: Types['Date Time']['Read'];
		organization: { __id: Organization['Read']['id'] } | [Organization['Read']];
		owns_credit_notification_for__feature:
			| { __id: Feature['Read']['id'] }
			| [Feature['Read']];
		id: Types['Integer']['Read'];
		is_sent_when_below__threshold: Types['Integer']['Read'];
		feature: { __id: Feature['Read']['id'] } | [Feature['Read']];
	};
	Write: {
		organization: Types['Integer']['Write'];
		owns_credit_notification_for__feature: Types['Integer']['Write'];
		is_sent_when_below__threshold: Types['Integer']['Write'];
	};
}

export interface PlanHasDiscountCode {
	Read: {
		plan: { __id: Plan['Read']['id'] } | [Plan['Read']];
		discount_code: Types['Short Text']['Read'];
		id: Types['Integer']['Read'];
	};
	Write: Record<string, never>;
}

export interface PlanFeature {
	Read: {
		plan: { __id: Plan['Read']['id'] } | [Plan['Read']];
		provides__feature: { __id: Feature['Read']['id'] } | [Feature['Read']];
		id: Types['Integer']['Read'];
		quantity: Types['Integer']['Read'];
		feature: { __id: Feature['Read']['id'] } | [Feature['Read']];
	};
	Write: Record<string, never>;
}

export interface PlanAddon {
	Read: {
		plan: { __id: Plan['Read']['id'] } | [Plan['Read']];
		offers__feature: { __id: Feature['Read']['id'] } | [Feature['Read']];
		id: Types['Integer']['Read'];
		base_price: Types['Integer']['Read'];
		can_self_serve: Types['Boolean']['Read'];
		bills_dynamically: Types['Boolean']['Read'];
		feature: { __id: Feature['Read']['id'] } | [Feature['Read']];
		is_offered_by__plan: { __id: Plan['Read']['id'] } | [Plan['Read']];
		subscription__discounts__plan__offers__feature?: Array<
			SubscriptionDiscountsPlanAddon['Read']
		>;
		subscription__discounts__plan_addon?: Array<
			SubscriptionDiscountsPlanAddon['Read']
		>;
		subscription_addon_discount?: Array<SubscriptionDiscountsPlanAddon['Read']>;
	};
	Write: Record<string, never>;
}

export interface SubscriptionDiscountsPlanAddon {
	Read: {
		subscription: { __id: Subscription['Read']['id'] } | [Subscription['Read']];
		discounts__plan_addon:
			| { __id: PlanAddon['Read']['id'] }
			| [PlanAddon['Read']];
		id: Types['Integer']['Read'];
		discount_percentage: Types['Real']['Read'];
		plan__offers__feature:
			| { __id: PlanAddon['Read']['id'] }
			| [PlanAddon['Read']];
		plan_addon: { __id: PlanAddon['Read']['id'] } | [PlanAddon['Read']];
		discounts__plan__offers__feature:
			| { __id: PlanAddon['Read']['id'] }
			| [PlanAddon['Read']];
	};
	Write: Record<string, never>;
}

export interface PublicDevice {
	Read: {
		is_of__device_type:
			| { __id: DeviceType['Read']['id'] }
			| [DeviceType['Read']];
		belongs_to__application:
			| { __id: Application['Read']['id'] }
			| [Application['Read']]
			| []
			| null;
		latitude: Types['Short Text']['Read'] | null;
		longitude: Types['Short Text']['Read'] | null;
		was_recently_online: Types['Boolean']['Read'];
	};
	Write: Record<string, never>;
}

export interface IdentityProvider {
	Read: {
		id: Types['Integer']['Read'];
		sso_identifier: Types['Short Text']['Read'];
		entry_point: Types['Text']['Read'];
		issuer: Types['Text']['Read'];
		certificate: Types['Text']['Read'];
		requires_signed_authn_response: Types['Boolean']['Read'];
		organization__is_authorized_by__identity_provider?: Array<
			IdentityProviderMembership['Read']
		>;
		identity_provider_membership?: Array<IdentityProviderMembership['Read']>;
		authorizes__organization?: Array<IdentityProviderMembership['Read']>;
		authorizes__organization__is_authorized_by__identity_provider?: Array<
			IdentityProviderMembership['Read']
		>;
		authorizes__identity_provider_membership?: Array<
			IdentityProviderMembership['Read']
		>;
	};
	Write: {
		sso_identifier: Types['Short Text']['Write'];
		entry_point: Types['Text']['Write'];
		issuer: Types['Text']['Write'];
		certificate: Types['Text']['Write'];
		requires_signed_authn_response: Types['Boolean']['Write'];
	};
}

export interface SamlAccount {
	Read: {
		id: Types['Integer']['Read'];
		belongs_to__user: { __id: User['Read']['id'] } | [User['Read']];
		was_generated_by__identity_provider:
			| { __id: IdentityProvider['Read']['id'] }
			| [IdentityProvider['Read']];
		remote_id: Types['Short Text']['Read'];
		display_name: Types['Short Text']['Read'] | null;
	};
	Write: Record<string, never>;
}

export interface IdentityProviderMembership {
	Read: {
		organization: { __id: Organization['Read']['id'] } | [Organization['Read']];
		is_authorized_by__identity_provider:
			| { __id: IdentityProvider['Read']['id'] }
			| [IdentityProvider['Read']];
		id: Types['Integer']['Read'];
		grants_access_to__team:
			| { __id: Team['Read']['id'] }
			| [Team['Read']]
			| []
			| null;
		identity_provider:
			| { __id: IdentityProvider['Read']['id'] }
			| [IdentityProvider['Read']];
		authorizes__organization:
			| { __id: Organization['Read']['id'] }
			| [Organization['Read']];
	};
	Write: {
		organization: Types['Integer']['Write'];
		is_authorized_by__identity_provider: Types['Integer']['Write'];
		grants_access_to__team: Types['Integer']['Write'] | null;
	};
}

export interface DeviceHistory {
	Read: {
		created_at: Types['Date Time']['Read'];
		id: Types['Integer']['Read'];
		end_timestamp: Types['Date Time']['Read'] | null;
		is_created_by__actor:
			| { __id: Actor['Read']['id'] }
			| [Actor['Read']]
			| []
			| null;
		is_ended_by__actor:
			| { __id: Actor['Read']['id'] }
			| [Actor['Read']]
			| []
			| null;
		tracks__device:
			| { __id: Device['Read']['id'] }
			| [Device['Read']]
			| []
			| null;
		tracks__actor: { __id: Actor['Read']['id'] } | [Actor['Read']] | [] | null;
		uuid: Types['Text']['Read'] | null;
		belongs_to__application:
			| { __id: Application['Read']['id'] }
			| [Application['Read']]
			| []
			| null;
		is_active: Types['Boolean']['Read'];
		is_running__release:
			| { __id: Release['Read']['id'] }
			| [Release['Read']]
			| []
			| null;
		is_pinned_on__release:
			| { __id: Release['Read']['id'] }
			| [Release['Read']]
			| []
			| null;
		is_managed_by__service_instance:
			| { __id: ServiceInstance['Read']['id'] }
			| [ServiceInstance['Read']]
			| []
			| null;
		os_version: Types['Short Text']['Read'] | null;
		os_variant: Types['Short Text']['Read'] | null;
		supervisor_version: Types['Short Text']['Read'] | null;
		is_of__device_type:
			| { __id: DeviceType['Read']['id'] }
			| [DeviceType['Read']]
			| []
			| null;
		cpu_id: Types['Short Text']['Read'] | null;
		should_be_managed_by__release:
			| { __id: Release['Read']['id'] }
			| [Release['Read']]
			| []
			| null;
	};
	Write: Record<string, never>;
}

export interface UserHasDirectAccessToApplication {
	Read: {
		user: { __id: User['Read']['id'] } | [User['Read']];
		has_direct_access_to__application:
			| { __id: Application['Read']['id'] }
			| [Application['Read']];
		application: { __id: Application['Read']['id'] } | [Application['Read']];
		is_directly_accessible_by__user:
			| { __id: User['Read']['id'] }
			| [User['Read']];
	};
	Write: Record<string, never>;
}

export interface ApplicationCanUseApplicationAsHost {
	Read: {
		application: { __id: Application['Read']['id'] } | [Application['Read']];
		can_use__application_as_host:
			| { __id: Application['Read']['id'] }
			| [Application['Read']];
	};
	Write: Record<string, never>;
}

export interface PublicOrganization {
	Read: {
		name: Types['Short Text']['Read'];
		handle: Types['Short Text']['Read'];
		is_of__application?: Array<Application['Read']>;
		application?: Array<Application['Read']>;
		owns__team?: Array<Team['Read']>;
		owns__credit_bundle?: Array<CreditBundle['Read']>;
		includes_legacy_link_to__user?: Array<User['Read']>;
		subscription?: Array<Subscription['Read']>;
	};
	Write: Record<string, never>;
}

export interface UserProfile {
	Read: {
		id: Types['Integer']['Read'];
		is_of__user: { __id: User['Read']['id'] } | [User['Read']];
		email: Types['Text']['Read'] | null;
		has_disabled_newsletter: Types['Boolean']['Read'];
		is_verified: Types['Boolean']['Read'];
		must_be_verified: Types['Boolean']['Read'];
		first_name: Types['Text']['Read'] | null;
		last_name: Types['Text']['Read'] | null;
		account_type: Types['Text']['Read'] | null;
		has_password_set: Types['Boolean']['Read'];
		company: Types['Text']['Read'] | null;
	};
	Write: Record<string, never>;
}

export default interface $Model {
	actor: Actor;
	user: User;
	api_key: ApiKey;
	application_type: ApplicationType;
	cpu_architecture: CpuArchitecture;
	device_family: DeviceFamily;
	device_manufacturer: DeviceManufacturer;
	device_type: DeviceType;
	image: Image;
	organization: Organization;
	service_instance: ServiceInstance;
	application: Application;
	application__has__env_var_name: ApplicationEnvironmentVariable;
	application__has__config_var_name: ApplicationConfigVariable;
	application__has__service_name: Service;
	application__has__service_name__has__label_name: ServiceLabel;
	application__has__service_name__has__name: ServiceEnvironmentVariable;
	application__has__tag_key: ApplicationTag;
	device: Device;
	device__has__env_var_name: DeviceEnvironmentVariable;
	device__has__config_var_name: DeviceConfigVariable;
	device__installs__image: ImageInstall;
	device__installs__application__has__service_name: ServiceInstall;
	device__installs__application__has__service_name__has__name: DeviceServiceEnvironmentVariable;
	device__has__tag_key: DeviceTag;
	release: Release;
	release__has__tag_key: ReleaseTag;
	image__is_part_of__release: ImageIsPartOfRelease;
	image__is_part_of__release__has__label_name: ImageLabel;
	image__is_part_of__release__has__name: ImageEnvironmentVariable;
	user__is_member_of__organization: OrganizationMembership;
	user__has__public_key: UserHasPublicKey;
	device_type__is_referenced_by__alias: DeviceTypeAlias;
	release__has__asset_key: ReleaseAsset;
	application_membership_role: ApplicationMembershipRole;
	credit_bundle: CreditBundle;
	delta: Delta;
	feature: Feature;
	oauth_application: OauthApplication;
	oauth_application_authorization: OauthApplicationAuthorization;
	organization_membership_role: OrganizationMembershipRole;
	plan: Plan;
	recovery_two_factor: RecoveryTwoFactor;
	social_service_account: SocialServiceAccount;
	subscription: Subscription;
	subscription_prepaid_addon: SubscriptionPrepaidAddon;
	support_tier: SupportTier;
	team: Team;
	invitee: Invitee;
	support_feature: SupportFeature;
	team__grants_access_to__application: TeamApplicationAccess;
	user__is_member_of__team: TeamMembership;
	user__is_member_of__application: UserIsMemberOfApplication;
	invitee__is_invited_to__application: InviteeIsInvitedToApplication;
	invitee__is_invited_to__organization: InviteeIsInvitedToOrganization;
	device__has__fqdn: DeviceDomainMapping;
	application__has__domain: ApplicationDomainMapping;
	application__has__build_var_name: BuildEnvironmentVariable;
	organization__has_private_access_to__device_type: OrganizationHasPrivateAccessToDeviceType;
	user__is_member_of__organization__has__tag_key: OrganizationMembershipTag;
	organization__owns_credit_notification_for__feature: OrganizationCreditNotification;
	plan__has__discount_code: PlanHasDiscountCode;
	plan__provides__feature: PlanFeature;
	plan__offers__feature: PlanAddon;
	subscription__discounts__plan__offers__feature: SubscriptionDiscountsPlanAddon;
	public_device: PublicDevice;
	identity_provider: IdentityProvider;
	saml_account: SamlAccount;
	organization__is_authorized_by__identity_provider: IdentityProviderMembership;
	device_history: DeviceHistory;
	user__has_direct_access_to__application: UserHasDirectAccessToApplication;
	application__can_use__application_as_host: ApplicationCanUseApplicationAsHost;
	public_organization: PublicOrganization;
	user_profile: UserProfile;
	// Synonyms
	application_environment_variable: ApplicationEnvironmentVariable;
	application_config_variable: ApplicationConfigVariable;
	service: Service;
	service_label: ServiceLabel;
	service_environment_variable: ServiceEnvironmentVariable;
	application_tag: ApplicationTag;
	device_environment_variable: DeviceEnvironmentVariable;
	device_config_variable: DeviceConfigVariable;
	image_install: ImageInstall;
	service_install: ServiceInstall;
	device_service_environment_variable: DeviceServiceEnvironmentVariable;
	device_tag: DeviceTag;
	release_tag: ReleaseTag;
	release_image: ImageIsPartOfRelease;
	image_label: ImageLabel;
	image_environment_variable: ImageEnvironmentVariable;
	organization_membership: OrganizationMembership;
	user_public_key: UserHasPublicKey;
	device_type_alias: DeviceTypeAlias;
	release_asset: ReleaseAsset;
	team_application_access: TeamApplicationAccess;
	team_membership: TeamMembership;
	user_application_membership: UserIsMemberOfApplication;
	application_invite: InviteeIsInvitedToApplication;
	organization_invite: InviteeIsInvitedToOrganization;
	device_domain_mapping: DeviceDomainMapping;
	application_domain_mapping: ApplicationDomainMapping;
	build_environment_variable: BuildEnvironmentVariable;
	organization_membership_tag: OrganizationMembershipTag;
	organization_credit_notification: OrganizationCreditNotification;
	plan_feature: PlanFeature;
	plan_addon: PlanAddon;
	subscription_addon_discount: SubscriptionDiscountsPlanAddon;
	identity_provider_membership: IdentityProviderMembership;
}
